### ISSUE TITLE
Websocket error 1002

### ISSUE THREAD

**Issue by nyok92** [alangecker/bigbluebutton-docker#1]
Hi, 
I apreciate your work on "dockerizing" BBB.
I had your setup working, but after a redeployment with last commit, i do have a connection error 1002 on websocket connection when i try to pass the echo test on a room.
All other fonctionnalities work as expected.
Do you have any idea where it does come from ?

I just replaced values in .env with mine, and did proxy the nginx docker (port 80) behind traefik.

Web console :
sip.js?v=887:8404 WebSocket connection to 'wss://**MYDOMAIN**/ws' failed: Error during WebSocket handshake: Unexpected response code: 502
 sip.transport | WebSocket connection error: {"isTrusted":true}

NGINX container:
[error] 6#6: *76 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.4.10, server: _, request: "GET /ws HTTP/1.1", upstream: "https://**MYPUBLICIPIP**:7443/ws", host: "**MYDOMAIN**"

**Comment by alangecker** [comment]
hey @nyok92 
thanks for your appreciation!

maybe first ensure, that freeswitch's wss port is open `7443`:
```
root@meet:~# ss -tlpen | grep 7443
LISTEN   0        64                   10.7.7.1:7443             0.0.0.0:*       users:(("freeswitch",pid=18170,fd=34)) uid:998 ino:50042781 sk:b4f <->    
```
important is also, that traefik points to `https://10.7.7.1:7443/ws` instead of the public ip `https://MYPUBLICIPIP:7443/ws`, since freeswitch only listens on `10.7.7.1` (you can see that in the `ss` output)

Most likely a change for `wss-binding` in this commit broke it for you:
https://github.com/alangecker/bigbluebutton-docker/commit/6248c9f93b91a257aefb35d0dd5fbc45e28160a6#diff-630b69824f4996e257cc0698f0ade312

**Comment by nyok92** [comment]
Hi, thanks.
I've jut made a new clone of your repo, then restarted bbb (with modifications).
Now everything 's back to normal/working.
Maybe i still had old docker volumes with bad configuration.
Thanks
