### ISSUE TITLE
how can we help to add coturn support ?

### ISSUE THREAD

**Issue by npettiaux** [alangecker/bigbluebutton-docker#5]
how can we help to add coturn support ?

**Comment by alangecker** [comment]
thanks for asking :)

just yesterday I've started a branch for the support of an external TURN server: [turn-support](https://github.com/alangecker/bigbluebutton-docker/compare/freeswitch-separation...alangecker:turn-support).
I'm still in the processing of testing it, but I would, if everything works, merge it in the next 2 days.

At first I thought about integrating coturn directly, but then decided not to. The purpose of a TURN server is, that people with restricted firewalls (only web access, blocked udp) are able to use WebRTC. Usually this is done by serving the TURN server via TLS on port 443, so the traffic is undistinguishable from HTTPS, but this requires a second IP since 443 is already taken by HTTPS.

The requirement of an own IP, low performance requirements, that you can use one TURN server for multiple BBB instances and the high complexity of integrating it directly in the docker setup led me to the opinion, that it makes much more sense to just rent a separate cheap VPS and install coturn there like described in https://docs.bigbluebutton.org/2.2/setup-turn-server.html

Nevertheless this setup could include coturn as a STUN server directly for increased privacy instead of using `stun.freeswitch.org` by default.

If you are motivated for that I would be happy about a Pull Request :)
Steps would be:
1. adding coturn to docker-compose.yml including port forwarding of 3478 (udp&tcp) 
2. coturn configuration
3. change STUN server in `sample.env`

**Comment by npettiaux** [comment]
thanks. I have no time now, nor too little knowledge, but I'll soon propose to my students to contribute. I am afraid though that I could not do that before Tuesday

**Comment by alangecker** [comment]
@npettiaux 
coturn is now included and fully automated! :)

**Comment by npettiaux** [comment]
does that mean that the installation of BBB on Debian is possible and simple ?

**Comment by npettiaux** [comment]
Or on a recent Ubuntu which is very similar

**Comment by alangecker** [comment]
> does that mean that the installation of BBB on Debian is possible and simple ?

yeps, you only need to follow the 5 steps in the [README.md](https://github.com/alangecker/bigbluebutton-docker/blob/v2.2.x/README.md)

thanks to docker encapsulation it is quite independend from the Operating System. I do have it running in production on debian 10 since a while, but is should be also stable on Ubuntu 20.04 or CentOS 8.
