### ISSUE TITLE
ERROR: Service 'html5' failed to build

### ISSUE THREAD

**Issue by hacko2** [alangecker/bigbluebutton-docker#94]
Get "ERROR: Service 'html5' failed to build" when compose up, why???

**Comment by hacko2** [comment]
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Killed
The command '/bin/sh -c cd ~/source     && ~/.meteor/meteor npm install --production     && ~/.meteor/meteor build --directory ~/app     && rm -r ~/source' returned a non-zero code: 137
ERROR: Service 'html5' failed to build

**Comment by alangecker** [comment]
I just tried it with the latest images without any issues
`./scripts/compose build --no-cache --pull html5`

Maybe there are some more log entries which could be relevant

And I once also had issues building the `html5` without any obvious error messages due to exceeded ram usage. Make sure, that you have at least ~4GB ram free for building the container :)

**Comment by hacko2** [comment]
Yes, just a ram problem, increase the KVM to 8gb and run well. Thanks!!
